@startuml Attributes
title Attributes System Class Diagram\n

class Player {
    +<<get>> Health : HealthAttribute
    +<<get>> Stamina : StaminaAttribute
    +<<get>> Poise : PoiseAttribute
    +<<get>> Status : StatusAttribute
    +<<get>> Attributes : AttributesContainer
}
Player *-- AttributesContainer

interface IAttribute<T : ValueType> {
    +<<get/set>> Value : T
    +event OnAttributeChanged(T oldValue, T newValue)
}

class HealthAttribute<float> implements IAttribute {
    +<<get/set>> Value : float
    +event OnAttributeChanged(float old, float new)
}
class StaminaAttribute<float> implements IAttribute
class PoiseAttribute<float> implements IAttribute

enum CharacterStatus {
    None
    Staggered
    IFrames
    Unstoppable
}
class StatusAttribute<CharacterStatus> implements IAttribute
StatusAttribute o-- CharacterStatus

class AttributesContainer
{
    +<<get>> Attributes : IAttribute[]
    +GetAttribute<T>() : T is ICharacterAttribute
}
AttributesContainer "1" o-- "1..*" IAttribute

class UIHealthBar <<MonoBehaviour>> {
    -OnHealthChanged(float old, float new)
}

PoiseAttribute --> PlayerBody : Change\nSignals

class PlayerBody {
    -OnPoiseChanged(float old, foat new)
    -PerformStagger()
}
note left : Perform stagger\nanimation when\nPoise value is\nchanged to "0".

HealthAttribute --> UIHealthBar : Change\nSignals

scale 1.5
hide empty members
@enduml