@startuml Attributes
title Attributes System Class Diagram

class Player
Player o-u- PlayerAttributeContainer

interface ICharacterAttribute {
}
abstract CharacterAttribute<T : ValueType> extends ICharacterAttribute  {
    +<<get/set>>Value : T
    +onAttributeChanged : event
}

class HealthAttribute<float> implements CharacterAttribute
class StaminaAttribute<float> implements CharacterAttribute
class PoiseAttribute<float> implements CharacterAttribute

enum CharacterStatus {
    None
    Staggered
    IFrames
    Unstoppable
}
class StatusAttribute<CharacterStatus> implements CharacterAttribute
StatusAttribute o-- CharacterStatus

abstract AttributesContainer
{
    +GetAttributes() : ICharacterAttribute[]
    +GetAttribute<T>() : T is ICharacterAttribute
}
AttributesContainer "1" o-- "1..*" ICharacterAttribute

class PlayerAttributeContainer
PlayerAttributeContainer o-u- StatusAttribute
PlayerAttributeContainer o-u- HealthAttribute
PlayerAttributeContainer o-u- StaminaAttribute
PlayerAttributeContainer o-u- PoiseAttribute

scale 1.3
hide empty members
@enduml